[package]
name = "env-check-domain"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
env-check-types = { path = "../env-check-types" }
serde_json.workspace = true
semver.workspace = true
