name: dist-pr

on:
  pull_request:

permissions:
  contents: read

jobs:
  dist-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo-dist plan
        uses: axodotdev/cargo-dist-action@v0.30.3
        with:
          command: plan
